# REASON: auto-regenerate .git-history.md from the last N commits so AI sessions have fresh recent-commit context instead of needing manual `git log` calls; replaces the role docs/progress files used to play; fails open without git.
"""Regenerate .git-history.md from the last N commits.

Runs as post-commit / post-merge / post-checkout hooks so the file
always reflects current HEAD. Output is gitignored -- single source
of truth is `git log`. AI reads this for context; it never edits.

N kept tight (10) so the bootstrap context stays cheap; older commits
are one `git log` away.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

OUTPUT = Path(".git-history.md")
N = 10


def main() -> int:
    try:
        log = subprocess.run(
            ["git", "log", f"-{N}",
             "--format=## %h -- %ai%n**%s**%n%n%b%n",
             "--no-merges"],
            capture_output=True, text=True, check=True,
            encoding="utf-8", errors="replace",
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        # Fail open: git unavailable or not a git repo.
        OUTPUT.write_text(
            f"# Recent commits -- last {N}\n\n"
            "_git unavailable -- run `git log` directly._\n",
            encoding="utf-8",
        )
        return 0

    OUTPUT.write_text(
        f"# Recent commits -- last {N}\n\n"
        "_Auto-regenerated by `scripts/refresh_history.py` (post-commit / "
        "post-merge / post-checkout hooks). Gitignored. AI: read-only -- "
        "the source of truth is `git log`, this file is a fresh cache._\n\n"
        + log,
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
