# REASON: auto-regenerate .gh-issues.md from active GitHub issues so AI has fresh backlog context instead of needing `gh issue list` round-trips per session; soft-passes when gh CLI is unauthenticated or offline.
"""Regenerate .gh-issues.md from active GitHub issues.

Runs as post-commit / post-merge / post-checkout hooks. Output is
gitignored -- source of truth is GitHub. AI reads this for context;
modifications go through `gh issue` CLI, not by editing the file.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

OUTPUT = Path(".gh-issues.md")


def main() -> int:
    # Explicit utf-8 + replace because issue titles/bodies routinely contain
    # em-dashes / arrows / other non-ASCII that decode-fail with Python's
    # default locale codec on Windows. errors='replace' guards against any
    # future surprise byte; the regenerated file is a convenience snapshot,
    # not authoritative.
    result = subprocess.run(
        ["gh", "issue", "list", "--state", "open", "--limit", "100",
         "--json", "number,title,labels,body,createdAt,updatedAt"],
        capture_output=True, text=True, check=False,
        encoding="utf-8", errors="replace",
    )
    if result.returncode != 0:
        OUTPUT.write_text(
            "# Active GitHub issues\n\n"
            "_gh CLI unavailable / unauthenticated. Run `gh auth login` "
            "and re-run `python scripts/refresh_issues.py`._\n",
            encoding="utf-8",
        )
        print("[refresh_issues] gh unavailable -- wrote stub", file=sys.stderr)
        return 0

    issues = json.loads(result.stdout) if (result.stdout or "").strip() else []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Active GitHub issues",
        "",
        f"_Auto-regenerated by `scripts/refresh_issues.py` (refreshed {now}). "
        "Gitignored. AI: read-only -- source of truth is GitHub. "
        "Modify via `gh issue {edit,close,create}`._",
        "",
        f"**{len(issues)} open.** Sorted by primary sprint/track label, then issue number.",
        "",
    ]

    def primary_label(issue: dict) -> str:
        for n in (l["name"] for l in issue["labels"]):
            if n.startswith("sprint:") or n.startswith("track:"):
                return n
        return "z-untagged"

    groups: dict[str, list[dict]] = {}
    # SERIAL_OK_LOOP: bounded N=100 issues; pure dict population
    for issue in issues:
        groups.setdefault(primary_label(issue), []).append(issue)

    # SERIAL_OK_LOOP: bounded by label count (~15); per-group sort + render
    for label in sorted(groups):
        lines.append(f"## {label}")
        lines.append("")
        # SERIAL_OK_LOOP: bounded N=issues-in-label (~5-15); per-issue rendering
        for issue in sorted(groups[label], key=lambda i: i["number"]):
            secondary = [
                l["name"] for l in issue["labels"]
                if not l["name"].startswith(("sprint:", "track:"))
            ]
            labels_str = f" -- {', '.join(secondary)}" if secondary else ""
            body = (issue["body"] or "").strip()
            if len(body) > 600:
                body = (
                    body[:600]
                    + f"\n\n_... (full body via `gh issue view {issue['number']}`)_"
                )
            lines.append(f"### #{issue['number']} -- {issue['title']}{labels_str}")
            lines.append("")
            if body:
                lines.append(body)
                lines.append("")
            lines.append("---")
            lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
